### ISSUE TITLE
Multiport for algorithm containers

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-node#51]
Now only one port is available for algorithms (8888). There are many cases where you want to use more than one port. I suggest the following changes:

- Add addition table to vantage6-server which has 3 columns: `result_id`, `label`, `port`. 
- Algorithm containers contain an `EXPOSE` entry for every port that the algorithm needs. And for every `EXPOSE` a label is given in the form of `LABEL p[PORT]='label' to label the exposed port.
- The node assigns multiple external ports and maps these to the exposed ports from the algorithm container

We could look into ways to let the API solve the issues regarding model change so that we are still compatible with 3.0.

**Comment by bartvanb** [comment]
- [ ] Modify node to read multiple ports and labels from Dockerfile
- [ ] Modify node to add `iptables` rules for each port
- [ ] Modify the server to have an additional table to save result_id+port+label
- [ ] Modify the node-server communication so that the result_id+port+labels are properly saved
- [ ] Modify the algorithm container client to be able to fetch a port by its label
- [ ] Modify algorithm boilerplate to give an example of these labels with a proper explanation
- [ ] Modify algorithm boilerplate to clarify how to fetch ports by their label

**Comment by bartvanb** [comment]
FYI: backwards database compatibility turns out not to be an issue. A new table holds the multiple port information. This database table is automatically created on server startup. The 'port' column in the result table is ignored from then onwards, but that should not be a problem.

**Comment by bartvanb** [comment]
Just created PRs for the server, node and client part of this. @frankcorneliusmartin could you test this with the Kaplan Meier? I haven't tested the client code changes but these were simple so I think that should work.

I think it would be good to wait with adding this to the algorithm boilerplate until this has been tested. Also it should not be in there if the feature has not been released.

**Comment by bartvanb** [comment]
There are a few things we still need to finish (see task list above)
